---
- src: https://github.com/geerlingguy/ansible-role-nginx.git
  scm: git
  name: geerlingguy.nginx
  version: 3.1.3

- src: https://github.com/geerlingguy/ansible-role-mysql.git
  scm: git
  name: geerlingguy.mysql
  version: 4.1.0

- src: https://github.com/robertdebock/ansible-role-php_fpm.git
  scm: git
  name: robertdebock.php_fpm
  version: 3.1.4
