---
- name: create new directory logs for docker nginx
  ansible.builtin.file:
    path: /opt/nginx/{{ item }}
    state: directory
  loop:
    - logs
    - conf
    - www

- name: replace nginx.conf
  template:
    src: templates/nginx.conf.j2
    dest: /opt/nginx/conf/nginx.conf

- name: create server.conf
  template:
    src: templates/server.conf.j2
    dest: /opt/nginx/conf/server.conf

- name: copy health
  ansible.builtin.copy:
    src: files/{{ item }}
    dest: /opt/nginx/www/{{ item }}
    owner: www-data
    group: www-data
    mode: '0644'
  loop:
    - index.html
    - health

- name: start docker nginx
  docker_container:
    name: nginx
    image: nginx:1.23.1
    state: started
    volumes:
      - /opt/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /opt/nginx/conf/server.conf:/etc/nginx/sites-enables/server.conf
      - /opt/nginx/logs:/var/log/nginx
      - /opt/nginx/www:/usr/share/nginx/html
    ports:
     - "8080:80"

- name: Check that you can connect (GET) to a page and it returns a status 200
  ansible.builtin.uri:
    url: http://localhost
    return_content: yes
  register: get

- name: print get
  debug:
   var: get.status
